### ISSUE TITLE
Old XRD format?

### ISSUE THREAD

**Issue by Gargron** [webfinger/client.webfinger.net#9]
So I notice there is no mention of the old XRD format for Webfinger in the current RFC, even though they are basically the same semantically, just encoded differently. Would it be useful for this tool to be able to parse XRD as well as JRD?

**Comment by willnorris** [comment]
I actually think it would be very confusing to support the old format, given that it's not actually part of webfinger.

But not only is the format different, there was a very different discovery flow that it used, [LRDD](https://tools.ietf.org/html/draft-hammer-discovery-06).  You first fetched `/.well-known/host-meta`, then followed a link there to get the descriptor of the original resource you cared about.  This two-step process was replaced with the single step `/.well-known/webfinger` that is used today.  So just supporting the old XRD file format without also supporting the old retrieval flow wouldn't really do any good.  And there's not much point in supporting the old discovery flow since I suspect all that would do is slow adoption of the proper WebFinger flow.

(Interestingly, gmail.com deployed the old flow, and it's still active today.  @bradfitz or I may finally get around to migrating that over to WebFinger, but it just hasn't happened yet.)

**Comment by Gargron** [comment]
Yes, see, I'm asking because GNU social still does the old flow (even though it prefers JRD version in the end iirc) and my own platform Mastodon is also built around the old flow (it also prefers JRD when it gets it but on the other hand it only offers XRD output atm, something I want to improve). So it's still somewhat widely adopted...
